//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Request_form.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Request
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RequestNote { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    }
}
